version: "3"
services:
  builder:
    build: .
    entrypoint: /usr/local/go/bin/go
    command: build -v
    volumes:
      - ./output:/go/src/github.com/cyberark/conjur-cli-go/output
    environment:
      GOOS:
      GOARCH:

  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  conjur:
    image: cyberark/conjur:latest
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    depends_on:
      - postgres

  cuke-master:
    image: registry2.itci.conjur.net/conjur-appliance-cuke-master:4.9-stable
    security_opt:
      - seccomp:unconfined # --security-opt seccomp=unconfined
    ports:
      - 443

  test:
    build: .
    ports:
        - "8080"
    depends_on:
      - conjur
    command: ci/test
    volumes:
      - ./output:/go/src/github.com/cyberark/conjur-cli-go/output
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:

  cli:
    image: cyberark/conjur-cli:5
    entrypoint: /bin/bash
    command: sleep inifinty
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:

  dev:
    privileged: true            # to allow debugging
    build: .
    ports:
        - "8080"
    depends_on:
      - conjur
    entrypoint: sleep infinity
    volumes:
      - .:/go/src/github.com/cyberark/conjur-cli-go

    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:
